[general]
use_julia_native_enum_type = true
print_using_CEnum = false
library_name = "cutest_lib_path"

[codegen]
use_julia_bool = true
always_NUL_terminated_string = false
use_ccall_macro = true

[codegen.macro]
macro_mode = "disable"
